### PR TITLE
Feature/vaadin examples

### PR DESCRIPTION
**Pull request by svenruppert**
updated the Vaadin 08 example
added the vaadin 10 example

### CODE REVIEW

**Comment by kenfinnigan** [comment]
ok to test

**Comment by svenruppert** [comment]
Hi, V8 is based on GWT V10 is based on web components/Polymer..  The way of coding is different, and V8 is the LTS version. Vaadin 11 will be the next LTS version, and the first based on web components..  If Vaadin 11 is available, I would provide a PR with an version update for the V10 one.

**Comment by svenruppert** [comment]
oh I forgot to say, Vaadin8 LTS and Vaadin 11 LTS are available at the same time.

**Comment by sberyozkin** [comment]
Thanks. This is a minor one, would you be OK with moving both vaadin8 and 10 modules being into a root folder 'vaadin' ?

**Comment by sberyozkin** [comment]
@kenfinnigan Ken, are you OK with the 2 vaadin sibling demos at the root level or would prefer having vaadin/vaadin8, vaadin/vaadin10 ? I can merge the current PR, np, or we can wait till this minor update is done, let me know please or merge if the current PR structure looks fine to you

**Comment by kenfinnigan** [comment]
Would be better to have under a common vadin directory, but wouldn't hold the PR up for that

**Comment by sberyozkin** [comment]
@svenruppert let us know please if you are OK with the common dir idea, I guess this can be done later as well...

**Comment by svenruppert** [comment]
No problem, will move it under the vaadin module..  Sorry for delay on my side.

**Comment by sberyozkin** [comment]
Sounds good, thanks

**Pull request merged**
