### PR TITLE
[THORN-2039] Adding a multitenancy demo

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
retest this please

**Comment by sberyozkin** [comment]
retest this please

**Comment by sberyozkin** [comment]
retest this please

**Comment by sberyozkin** [comment]
retest this please

**Comment by kenfinnigan** [comment]
add to whitelist

**Comment by kenfinnigan** [comment]
retest this please

**Comment by sberyozkin** [comment]
retest this please

**Pull request merged**
