### PR TITLE
Gradle Samples: Integration Test

### PR DESCRIPTION
**Pull request by roguexz**
Add an integration test setup which leverages the Gradle Test Kit for performing basic sanity checks on the included projects. At a minimum, the integration tests will execute `clean` & `build` to verify that nothing is breaking.

### CODE REVIEW

**Comment by roguexz** [comment]
As promised, here are the integration tests that I will be running before raising another PR on the core project :)

**Comment by Ladicek** [comment]
How is this test executed? Will it run during the standard Maven build?

**Comment by roguexz** [comment]
Not yet. It is currently in a standalone mode. I wanted you to review the changes once before asking you if we should integrate from Maven to Gradle at this project folder.

Currently, the only integration between the two build systems is configured for the [jaxrs-cdi](https://github.com/thorntail/thorntail-examples/tree/master/gradle-examples/jaxrs-cdi) module. If we pull up that integration test to the `gradle-examples` folder, then we can verify the `build` task across all the Gradle examples. Does that sound like something that we would like to have for this project?

**Comment by roguexz** [comment]
Pushed a commit that will execute the Gradle tests as part of the CI builds. I know it works on Mac, so Linux should be fine. I would like to see its behavior on the Windows CI.

**Comment by roguexz** [comment]
Looks like there is some connectivity issue. Making a small change that will print the test stdout & stderr to the console logs.

**Comment by roguexz** [comment]
@Ladicek Can you help me with the correct configurations that I should add for the target repositories?

I am seeing that it is unable to download the following,
```
[Fatal Error] gradle-tooling-api-5.6.2.pom:2:10: Already seen doctype.
```

Is there a way for me to define a separate virtual repository for pulling in the Gradle tooling jar?

If not, then please don't merge this PR yet as I would like to fix the issue where the arquillian test uses the MavenResolver despite being run from Gradle.

**Comment by Ladicek** [comment]
I'm trying to add https://repo.gradle.org/gradle/libs-releases-local/ to our Nexus, but no luck so far :-) Hopefully I'll be able to do it today, then I'll let Jenkins rerun the tests.

**Comment by Ladicek** [comment]
retest this please

**Comment by Ladicek** [comment]
(The Gradle repository should be added to Nexus now :-) )

**Comment by Ladicek** [comment]
It's still failing, and the error seems to be

```
Failed downloading io/thorntail/examples/gradle/library-module/0.0.0/library-module-0.0.0.pom from http://nexus.ci.obsidian.local/content/groups/public/. Reason: 
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.thorntail.examples.gradle:library-module:pom:0.0.0 in nexus-mirror (http://nexus.ci.obsidian.local/content/groups/public/)
```

I think `io.thorntail.examples.gradle:library-module` is something that the example itself should provide, so not sure why it's looking into a remote repository...?

**Comment by Ladicek** [comment]
Perhaps it's the Arquillian adapter who tries to download this library, because it expects it runs in a Maven environment...? Not sure.

**Comment by roguexz** [comment]
Let me look at the logs and get back to you on this one.

**Comment by roguexz** [comment]
Interestingly, I am able to execute the builds even when I am completely offline. I have excluded the `gradle-examples` project from being run right now. The samples are still useful to folks who are looking for them.

I have an idea of why this is happening, but can't say for sure. It has to do with the way I am exporting the dependencies of a project to framework.

Would you be ok to merge this PR while I work on investigating the underlying issue?

**Comment by Ladicek** [comment]
Windows failure is due to disk running out of space.

retest this please

**Comment by Ladicek** [comment]
I'll wait a few days if you're able to figure it out quickly, and will merge then if it takes you longer.

**Comment by Ladicek** [comment]
@roguexz Just submit another PR when you figure out the tests, thanks :-)

**Comment by roguexz** [comment]
Thanks @Ladicek . I haven't forgotten about it. I have been writing multiple test cases for verifying the expected behavior. I _believe_ I might have a solution that would both simplify and resolve these issues in an elegant manner. Would you want me to initiate the proposal on Google groups or directly as part of the PR? I would prefer PR, but wanted to gather your inputs as well.

**Comment by Ladicek** [comment]
PR is good, thanks!

**Pull request merged**
