### PR TITLE
THORN-2310 Add snapshot repository to gradle examples

### PR DESCRIPTION
**Pull request by TomasHofman**
...so that tt-examples master branch builds without having to install current
tt master locally.

https://issues.jboss.org/browse/THORN-2310

### CODE REVIEW

**Comment by Ladicek** [comment]
I wonder if this is also required for the `repositories` block outside the `buildscript` block?

**Comment by TomasHofman** [comment]
But of course it is, I was thinking about the gradle-plugin and forgot all about the dependencies... Will update.

**Comment by Ladicek** [comment]
It's been a while (sorry about that!), so I'd like to have another CI run before merging.

retest this please

**Comment by Ladicek** [comment]
The Windows failure is a known intermittent issue that is unrelated.

**Pull request merged**
