### PR TITLE
THORN-2285 Adapting JPA & JAXRS & CDI example as a gradle project

### PR DESCRIPTION
**Pull request by TomasHofman**
This reproduces issue described in THORN-2285.

https://issues.jboss.org/browse/THORN-2285

### CODE REVIEW

**Comment by Ladicek** [comment]
add to whitelist

**Comment by Ladicek** [comment]
CC @roguexz

**Comment by TomasHofman** [comment]
@roguexz I noticed the gradle plugin doesn't yet support running the application (which would be a requirement for executing integration tests?). Is that something you are already working on? If not, I could take a look.

**Comment by roguexz** [comment]
> @roguexz I noticed the gradle plugin doesn't yet support running the application (which would be a requirement for executing integration tests?). Is that something you are already working on? If not, I could take a look.

Currently we do not have any task for "starting" & "stopping" the container in order to perform integration tests. As a workaround, I have been creating Arquillian based tests to simulate the same behavior. Hence my work on ensuring that the execution both within and outside of a test are as close as possible.

You could either consider adding an Arquillian test, or look at designing & implementing the stubs required to achieve integration tests. I am currently not looking at that aspect, so it is all yours if you would like to take stab at it :)

**Comment by TomasHofman** [comment]
Thanks @roguexz, I implemented all your suggestions.

Couple of notes:
* I had to add a maven repository at https://repo.gradle.org/gradle/libs-releases-local, otherwise I weren't able to obtain org.gradle:gradle-tooling-api:5.0. So I added the repo also in the other gradle example jaxrs-cdi.
* I was playing with Arquillian tests, specifically the ones with @DefaultDeployment annotation. Whenever I change the type in the annotation from JAR to WAR, I get some wierd Weld exceptions during container boot. And btw is @DefaultDeployment supposed to do what I think - deploy the artifact produced by given module?

**Comment by Ladicek** [comment]
> is @DefaultDeployment supposed to do what I think - deploy the artifact produced by given module?

No. See `DefaultDeploymentScenarioGenerator`. Basically, if the test is `com.example.foo.bar.MyTest`, a deployment gets created which includes all classes from `com.example.foo.bar` and subpackages. And some resources.

**Comment by roguexz** [comment]
@TomasHofman 
> 
> * I had to add a maven repository at https://repo.gradle.org/gradle/libs-releases-local, otherwise I weren't able to obtain org.gradle:gradle-tooling-api:5.0. So I added the repo also in the other gradle example jaxrs-cdi.

Interesting, I don't remember having to add that. Could be because I use Gradle a lot and something would have pulled it in. But I can look at that in a subsequent commit.

> * I was playing with Arquillian tests, specifically the ones with @DefaultDeployment annotation. Whenever I change the type in the annotation from JAR to WAR, I get some wierd Weld exceptions during container boot. And btw is @DefaultDeployment supposed to do what I think - deploy the artifact produced by given module?

The `DefaultDeployment( type = WAR)` tends to bundle in all Thorntail dependencies in to the `WEB-INF/lib` folder ... this causes CDI to initialize beans that are not supposed to be initialized.

In my internal project, I have been configuring the `WARArchive` manually and putting necessary files in to it. You may need to do the same for now (i.e., Do not use `DefaultDeployment` and instead have a static method that returns the `Archive` explicitly).

I am still tweaking my internal project and once I believe that the changes are stable enough (i.e., works from IDE and CLI) I shall include them as part of the examples.

**Comment by TomasHofman** [comment]
@Ladicek got it, thanks! :)

@roguexz yes, I specified the deployment manually in the end, so an arq test is there and working. Thanks for your comments!

**Comment by roguexz** [comment]
Changes look good @TomasHofman 
@Ladicek all yours for the merge :)

**Pull request merged**
