### PR TITLE
kotlin and vaadin version updates, plus next V14 LTS demo

### PR DESCRIPTION
**Pull request by svenruppert**

### CODE REVIEW

**Comment by Ladicek** [comment]
ok to test

**Comment by Ladicek** [comment]
CI fails because we proxy all Maven downloads to our own Nexus, which doesn't proxy the Vaadin prereleases repo. Will Vaadin 14 be available in Central?

**Comment by svenruppert** [comment]
Sure, the final will be in maven central.. I could deactivate this module first and reactivate it later again.

Von meinem iPhone gesendet

**Comment by Ladicek** [comment]
That would be great, thanks!

**Comment by svenruppert** [comment]
@Ladicek module is deactivated

**Comment by Ladicek** [comment]
Thanks!

**Pull request merged**
