### PR TITLE
Microprofile OpenTracing example

### PR DESCRIPTION
**Pull request by pavolloffay**
If you want to try it follow the instructions from existing opentracing example

### CODE REVIEW

**Comment by heiko-braun** [comment]
add to whitelist

**Comment by kenfinnigan** [comment]
@pavolloffay, can you take a look at resolving the conflicts so we can merge this? Thanks

**Comment by pavolloffay** [comment]
sure I will have a look

**Comment by pavolloffay** [comment]
@kenfinnigan the build fails on 

> The project org.wildfly.swarm.examples:examples-microprofile-opentracing:2018.2.0-SNAPSHOT (/home/ploffay/projects/wildfly-swarm-examples/microprofile-opentracing/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.wildfly.swarm:microprofile-opentracing:jar is missing. @ org.wildfly.swarm.examples:examples-microprofile-opentracing:[unknown-version], /home/ploffay/projects/wildfly-swarm-examples/microprofile-opentracing/pom.xml, line 47, column 17

MP-OT fraction does not exists under `org.wildfly.swarm`. It's been merged after rename. This has to wait until rename happes in this repo. Probbaly in https://github.com/thorntail/thorntail-examples/pull/184

**Comment by pavolloffay** [comment]
@kenfinnigan rebased and fixed.

**Comment by pavolloffay** [comment]
@kenfinnigan @heiko-braun can this be merged?

**Pull request merged**
